Change TS compiler target to es2021 b/c of .replaceAll() method
without this change I get:

src/test/utils.ts:77:48 - error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.

77     const timeStamp = new Date().toISOString().replaceAll(':', '-');