Downgrade jest and @types/jest back to v29
it looks like v30 introduces some backwards incompatible changes
or types aren't updated yet:

Error: src/test/unit-tests/parsing.test.ts(243,31): error TS2339: Property 'toThrowError' does not exist on type 'JestMatchers<() => number>'.