Remove unused dev dependency - mocha
there are no test files here, testing is done in docs/smart-contract-development/with-hardhat/
and the `yarn test` command fails with:

Error: No test files found: "test"