Assert the correct error message when proxy doesn't have enough CTC
when executing commands with a proxy configured the check for enough
funds should check that:

 - proxy account has enough funds to pay transaction fees
 - delegate account has enough funds for the actual amount used by
   the transaction, e.g. a bond amount!

The command should print a human readable error coming from:
lib/tx.ts::requireKeyringHasSufficientFunds() -> requireEnoughFundsToSend()

instead of sending the transaction and then crashing with a traceback:

Sending transaction...
2024-04-05 14:56:03        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
2024-04-05 14:56:03        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:23
        throw new error_js_1.default(`${code}: ${message}${formatErrorData(data)}`, code, data);
              ^

RpcError: 1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low
    at checkError (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:23:15)
    at RpcCoder.decodeResponse (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/@polkadot/rpc-provider/cjs/coder/index.js:39:9)
    at WsProvider.__internal__onSocketMessageResult (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:413:51)
    at WebSocket.__internal__onSocketMessage (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/@polkadot/rpc-provider/cjs/ws/index.js:402:20)
    at callListener (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:518:28)
    at Receiver.receiverOnMessage (/home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:518:28)
    at /home/gluwa/creditcoin-3.0/creditcoin3/cli/node_modules/ws/lib/receiver.js:608:16

Node.js v20.12.0

WARNING: this change will cause tests to fail b/c the current
implementation is incorrect. This is documented in more details in
CSUB-1030.