Build precompiles metadata for a few more CI jobs
b/c we have symlinks pointing to this metadata it needs to be generated,
otherwise we get errors like:

Error: src/test/blockchain-tests/precompiles/substrate-transfer.test.ts(2,34): error TS2307:
Cannot find module '../artifacts/substrate_transfer.json' or its corresponding type declarations.

This commit fixes the unit-test-cli and integration-test-cli jobs!

Examples of failures:
https://github.com/gluwa/creditcoin3-next/actions/runs/12413701066/job/34656151394?pr=6