Use subxt-cli version 0.37.0 because it works
Version 0.38.0 fails, see
https://github.com/gluwa/creditcoin3-next/actions/runs/11795118796/job/32855382460?pr=6

```
 error[E0658]: use of unstable library feature 'error_in_core'
  --> /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/frame-decode-0.5.0/src/decoding/extrinsic_decoder.rs:56:6
   |
56 | impl core::error::Error for ExtrinsicDecodeError {}
   |      ^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #103765 <https://github.com/rust-lang/rust/issues/103765> for more information
```