Remove --release when building WASM blobs with srtool
otherwise we see this error:

 error: the argument '--release' cannot be used with '--profile <PROFILE-NAME>'

in gluwa/creditcoin3 this has been removed here:
https://github.com/gluwa/creditcoin3/commit/8cffec8415ca90c275fabf66d3073d8975fe7c46