Fix recursive trait bounds exposed with rustc 1.75.0
cargo llvm-cov was hitting this issue:

error[E0275]: overflow evaluating the requirement `<Runtime as pallet_grandpa::Config>::KeyOwnerProof == _`

which is documented upstream in
https://github.com/rust-lang/rust/issues/117211
https://github.com/paritytech/polkadot-sdk/issues/2641

and fixed in polkadot-sdk v1.6.0 and later, see
https://github.com/paritytech/polkadot-sdk/pull/2644