WARNING: Claim -> ClaimOld for pallets/prover/ & precompiles/claim/
the original type was renamed in 17310a29 which is a left-over from
fixes after a Merge commit, however changes don't seem to have been
applied in these 2 directories, or maybe there are some conflicting new
changes coming in from integrate-claim-queries branch itself, IDK.

Without this commit the compiler gives the following list of errors:

   Compiling pallet-prover v3.31.0 (/home/gluwa/creditcoin-3.0/creditcoin3-next/pallets/prover)
error[E0106]: missing lifetime specifier
  --> pallets/prover/src/lib.rs:85:40
   |
85 |         Value = BTreeMap<T::Hash, Claim<<T as Config>::Address>>,
   |                                        ^ expected named lifetime parameter
   |
help: consider introducing a named lifetime parameter
   |
82 ~     pub type ProverClaims<'a, T: Config> = StorageMap<
83 |         Hasher = Blake2_128Concat,
84 |         Key = T::AccountId,
85 ~         Value = BTreeMap<T::Hash, Claim<'a, <T as Config>::Address>>,
   |

error[E0106]: missing lifetime specifier
   --> pallets/prover/src/lib.rs:138:18
    |
138 |             Claim<<T as Config>::Address>,
    |                  ^ expected named lifetime parameter
    |
help: consider introducing a named lifetime parameter
    |
126 ~     pub enum Event<'a, T: Config> {
127 |         /// Emitted when an prover is properly registered with the prover system
  ...
137 |             T::Hash,
138 ~             Claim<'a, <T as Config>::Address>,
    |

error[E0106]: missing lifetime specifier
   --> pallets/prover/src/lib.rs:138:18
    |
138 |             Claim<<T as Config>::Address>,
    |                  ^ expected named lifetime parameter
    |
    = note: for more information on higher-ranked polymorphism, visit https://doc.rust-lang.org/nomicon/hrtb.html
help: consider making the bound lifetime-generic with a new `'a` lifetime
    |
15  ~ for<'a> #[frame_support::pallet]
16  | pub mod pallet {
  ...
137 |             T::Hash,
138 ~             Claim<'a, <T as Config>::Address>,
    |
help: consider introducing a named lifetime parameter
    |
126 ~     pub enum Event<'a, T: Config> {
127 |         /// Emitted when an prover is properly registered with the prover system
  ...
137 |             T::Hash,
138 ~             Claim<'a, <T as Config>::Address>,
    |

error[E0106]: missing lifetime specifier
   --> pallets/prover/src/lib.rs:138:18
    |
138 |             Claim<<T as Config>::Address>,
    |                  ^ expected named lifetime parameter
    |
help: consider making the bound lifetime-generic with a new `'a` lifetime
    |
15  ~ for<'a> #[frame_support::pallet]
16  | pub mod pallet {
  ...
137 |             T::Hash,
138 ~             Claim<'a, <T as Config>::Address>,
    |
help: consider introducing a named lifetime parameter
    |
126 ~     pub enum Event<'a, T: Config> {
127 |         /// Emitted when an prover is properly registered with the prover system
  ...
137 |             T::Hash,
138 ~             Claim<'a, <T as Config>::Address>,
    |

error[E0106]: missing lifetime specifier
   --> pallets/prover/src/lib.rs:222:25
    |
222 |             claim: Claim<<T as Config>::Address>,
    |                         ^ expected named lifetime parameter
    |
help: consider introducing a named lifetime parameter
    |
168 ~     #[pallet::call'a, ]
169 |     impl<T: Config> Pallet<T> {
  ...
221 |             origin: OriginFor<T>,
222 ~             claim: Claim<'a, <T as Config>::Address>,
    |

error[E0106]: missing lifetime specifier
   --> pallets/prover/src/lib.rs:222:25
    |
222 |             claim: Claim<<T as Config>::Address>,
    |                         ^ expected named lifetime parameter
    |
help: consider making the bound lifetime-generic with a new `'a` lifetime
    |
15  ~ for<'a> #[frame_support::pallet]
16  | pub mod pallet {
  ...
221 |             origin: OriginFor<T>,
222 ~             claim: Claim<'a, <T as Config>::Address>,
    |
help: consider introducing a named lifetime parameter
    |
168 ~     #[pallet::call'a, ]
169 |     impl<T: Config> Pallet<T> {
  ...
221 |             origin: OriginFor<T>,
222 ~             claim: Claim<'a, <T as Config>::Address>,
    |

error[E0106]: missing lifetime specifier
  --> pallets/prover/src/lib.rs:85:40
   |
85 |         Value = BTreeMap<T::Hash, Claim<<T as Config>::Address>>,
   |                                        ^ expected named lifetime parameter
   |
   = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime, but this is uncommon unless you're returning a borrowed value from a `const` or a `static`, or if you will only have owned values
   |
85 |         Value = BTreeMap<T::Hash, Claim<'static, <T as Config>::Address>>,
   |                                         ++++++++

error[E0277]: the trait bound `<T as pallet::Config>::Address: ClaimQuery` is not satisfied
   --> pallets/prover/src/lib.rs:138:13
    |
138 |             Claim<<T as Config>::Address>,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ClaimQuery` is not implemented for `<T as pallet::Config>::Address`
    |
note: required by a bound in `Claim`
   --> /home/gluwa/creditcoin-3.0/creditcoin3-next/primitives/prover/src/claim.rs:90:25
    |
90  | pub struct Claim<'a, Q: ClaimQuery> {
    |                         ^^^^^^^^^^ required by this bound in `Claim`
help: consider introducing a `where` clause, but there might be an alternative better way to express this requirement
    |
126 |     pub enum Event<T: Config> where <T as pallet::Config>::Address: ClaimQuery {
    |                               ++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: the trait bound `<T as pallet::Config>::Address: ClaimQuery` is not satisfied
  --> pallets/prover/src/lib.rs:15:1
   |
15 | #[frame_support::pallet]
   | ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ClaimQuery` is not implemented for `<T as pallet::Config>::Address`
   |
note: required by a bound in `Claim`
  --> /home/gluwa/creditcoin-3.0/creditcoin3-next/primitives/prover/src/claim.rs:90:25
   |
90 | pub struct Claim<'a, Q: ClaimQuery> {
   |                         ^^^^^^^^^^ required by this bound in `Claim`
   = note: this error originates in the derive macro `frame_support::__private::codec::Encode` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `<T as pallet::Config>::Address: ClaimQuery` is not satisfied
  --> pallets/prover/src/lib.rs:15:1
   |
15 | #[frame_support::pallet]
   | ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ClaimQuery` is not implemented for `<T as pallet::Config>::Address`
   |
note: required by a bound in `Claim`
  --> /home/gluwa/creditcoin-3.0/creditcoin3-next/primitives/prover/src/claim.rs:90:25
   |
90 | pub struct Claim<'a, Q: ClaimQuery> {
   |                         ^^^^^^^^^^ required by this bound in `Claim`
   = note: this error originates in the derive macro `frame_support::__private::codec::Decode` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `<T as pallet::Config>::Address: ClaimQuery` is not satisfied
  --> pallets/prover/src/lib.rs:15:1
   |
15 | #[frame_support::pallet]
   | ^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ClaimQuery` is not implemented for `<T as pallet::Config>::Address`
   |
note: required by a bound in `Claim`
  --> /home/gluwa/creditcoin-3.0/creditcoin3-next/primitives/prover/src/claim.rs:90:25
   |
90 | pub struct Claim<'a, Q: ClaimQuery> {
   |                         ^^^^^^^^^^ required by this bound in `Claim`
   = note: this error originates in the derive macro `frame_support::__private::scale_info::TypeInfo` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `<T as pallet::Config>::Address: ClaimQuery` is not satisfied
   --> pallets/prover/src/lib.rs:222:20
    |
222 |             claim: Claim<<T as Config>::Address>,
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ClaimQuery` is not implemented for `<T as pallet::Config>::Address`
    |
note: required by a bound in `Claim`
   --> /home/gluwa/creditcoin-3.0/creditcoin3-next/primitives/prover/src/claim.rs:90:25
    |
90  | pub struct Claim<'a, Q: ClaimQuery> {
    |                         ^^^^^^^^^^ required by this bound in `Claim`
help: consider introducing a `where` clause, but there might be an alternative better way to express this requirement
    |
168 |     #[pallet::call where <T as pallet::Config>::Address: ClaimQuery]
    |                    ++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: the trait bound `<T as pallet::Config>::Address: ClaimQuery` is not satisfied
   --> pallets/prover/src/lib.rs:222:20
    |
222 |             claim: Claim<<T as Config>::Address>,
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ClaimQuery` is not implemented for `<T as pallet::Config>::Address`
    |
note: required by a bound in `Claim`
   --> /home/gluwa/creditcoin-3.0/creditcoin3-next/primitives/prover/src/claim.rs:90:25
    |
90  | pub struct Claim<'a, Q: ClaimQuery> {
    |                         ^^^^^^^^^^ required by this bound in `Claim`
help: consider further restricting the associated type
    |
223 |         ) -> DispatchResult where <T as pallet::Config>::Address: ClaimQuery {
    |                             ++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: the trait bound `<T as pallet::Config>::Address: ClaimQuery` is not satisfied
   --> pallets/prover/src/lib.rs:305:21
    |
305 |             claim: &Claim<<T as Config>::Address>,
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ClaimQuery` is not implemented for `<T as pallet::Config>::Address`
    |
note: required by a bound in `Claim`
   --> /home/gluwa/creditcoin-3.0/creditcoin3-next/primitives/prover/src/claim.rs:90:25
    |
90  | pub struct Claim<'a, Q: ClaimQuery> {
    |                         ^^^^^^^^^^ required by this bound in `Claim`
help: consider further restricting the associated type
    |
307 |         ) -> DispatchResult where <T as pallet::Config>::Address: ClaimQuery {
    |                             ++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: the trait bound `<T as pallet::Config>::Address: ClaimQuery` is not satisfied
   --> pallets/prover/src/lib.rs:341:21
    |
341 |             claim: &Claim<<T as Config>::Address>,
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ClaimQuery` is not implemented for `<T as pallet::Config>::Address`
    |
note: required by a bound in `Claim`
   --> /home/gluwa/creditcoin-3.0/creditcoin3-next/primitives/prover/src/claim.rs:90:25
    |
90  | pub struct Claim<'a, Q: ClaimQuery> {
    |                         ^^^^^^^^^^ required by this bound in `Claim`
help: consider further restricting the associated type
    |
343 |         ) -> DispatchResult where <T as pallet::Config>::Address: ClaimQuery {
    |                             ++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: the trait bound `<T as pallet::Config>::Address: ClaimQuery` is not satisfied
   --> pallets/prover/src/lib.rs:222:20
    |
222 |             claim: Claim<<T as Config>::Address>,
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ClaimQuery` is not implemented for `<T as pallet::Config>::Address`
    |
note: required by a bound in `Claim`
   --> /home/gluwa/creditcoin-3.0/creditcoin3-next/primitives/prover/src/claim.rs:90:25
    |
90  | pub struct Claim<'a, Q: ClaimQuery> {
    |                         ^^^^^^^^^^ required by this bound in `Claim`
help: consider further restricting the associated type
    |
168 |     #[pallet::call where <T as pallet::Config>::Address: ClaimQuery]
    |                    ++++++++++++++++++++++++++++++++++++++++++++++++

error[E0277]: the trait bound `<T as pallet::Config>::Address: ClaimQuery` is not satisfied
  --> pallets/prover/src/lib.rs:85:35
   |
85 |         Value = BTreeMap<T::Hash, Claim<<T as Config>::Address>>,
   |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ClaimQuery` is not implemented for `<T as pallet::Config>::Address`
   |
note: required by a bound in `Claim`
  --> /home/gluwa/creditcoin-3.0/creditcoin3-next/primitives/prover/src/claim.rs:90:25
   |
90 | pub struct Claim<'a, Q: ClaimQuery> {
   |                         ^^^^^^^^^^ required by this bound in `Claim`
help: consider further restricting the associated type
   |
80 |     #[pallet::storage, <T as pallet::Config>::Address: ClaimQuery]
   |                      ++++++++++++++++++++++++++++++++++++++++++++

Some errors have detailed explanations: E0106, E0277.
For more information about an error, try `rustc --explain E0106`.
error: could not compile `pallet-prover` (lib) due to 19 previous errors
warning: build failed, waiting for other jobs to finish...