feat: ccnext indexer (#390)
* chore: move indexer here

* chore: move readme here

* Add cc3-indexer to JavaScript CI jobs matrix

- enable prettier
- enable eslint
- enable typecheck

* Keep yarn.lock under version control as we do with all other TS directories

* Yarn format everything

* Make eslint happy

* Resolve typecheck issues

- adds missing dependencies

* Add cc3-indexer to Dependabot config

* use ss58Format to decode address.

* Save attestors to allow query by attestor and chain key

* introduced attestors entity with indexed field like attestorId/chain key

* Move workflow file in the appropriate directory

* Update names, use the same Ubuntu & Node.js version like everywhere else

WARNING: upstream BASE container uses node:lts-alpine which is a rolling
target! See:
https://github.com/subquery/subql/blob/main/packages/node/Dockerfile#L19

* Adjust working directory accordingly

* Remove now unused release workflow & script

* Make @subql/node a development dependency

instead of installing it globally

* Remove 'latest' version specifier & pin to a specific number

in order to avoid surprises in the future

* Remove hard-coded directory argument to `subql-node test`

and replace it with the current directory inside these CI steps
operate

* disable indexing of transfer for now.

* Update attestor entity on Chill and Activated event.

* make id unique for attestor entity when index elected event.

* indexer fix lint.

* introduced checkpoints.

* added lastcheckpointsClearedBlockNumber

* added logs about cleared checkpoints updated.

* added stashId

* fix format.

* checkpoint reached -> checkpoints.

* event Digest -> digest.

* bls pub key

* bls pub key

* format.

* index BlockAttested event

* store block attestors in separate table.

* fix lint and build.

* rename, fix addressed comments from review.

* remove unnecessary clone in tests.

* introduce shouldExists so will throw error when does not exists.

* rename eventChainKey into chainKey

* introduced map table attestors/attestation

* fix bug in checkAndGetAttestor function.

* remove attestors, and make prevDigest optional.

* fix typo.

* feat: rework indexer compose (#392)

* feat: rework indexer compose

* chore: some rework

* chore: some rework (broken)

* CSUB-1459: Fix container CMD (#394)

* Fix ENTRYPOINT & CMD directives for docker image

- Remove ENTRYPOINT definition b/c there is no such command `subql-node`
  installed in the docker image
- The actual ENTRYPOINT is /bin/run wrapped inside a BusyBox shell
- Adjust CMD arguments to follow the same syntax as upstream (not sure
  if strictly necessary but trying to minimize all differences)

see base image definition at:
https://github.com/subquery/subql/blob/main/packages/node/Dockerfile

* Explicitly define host.docker.internal in compose file

otherwise network connectivity b/w hosts (DNS resolution) won't work.
Confirmed ping works!

https://docs.docker.com/reference/compose-file/services/#extra_hosts

* chore: some rework

---------

Co-authored-by: Alexander Todorov <alex.todorov@gluwa.com>

* Build gluwa/cc3-indexer Docker image for release

assumes cc3-indexer/Dockerfile

* Build cc3-indexer docker image for testing too

also list all of the built images in case we need to debug something

* Adopt the `gluwa/creditcoin3-next:indexer-for-<version>` naming convention

upon release that would become something like

gluwa/creditcoin3-next:indexer-for-X.Y.Z-testnet

* feat: index prover contract events (#396)

* feat: index prover contract creation

* feat: query submitted event + wip other

* feat: add other events to index

* chore: edit build command

* chore: fmt

* chore: fix chainkey schema type

* feat: rework contract and chain query indexer type

* chore: update codegen

* feat: some impactful changes to prover contract

* chore: finish indexing

* chore: update schema

* chore: update abis

* chore: remove line

* chore: revert removed code

* fix: properly handle verifier state

* call .save() method on attestor entity to store into postgres. readme.

* Auto-update metadata & TypeScript type definitions

* feat: align indexer to new prover contract (#411)

* feat: add display name for prover contract

* chore: emit some more fields in constructor contract

* feat: complete index new events

* chore: add exception to make ingesting devnet work

* chore: remove unused package json file

* chore: rework & fix tests

* chore: update indexer workflow

* feat: indexer genesis state (#416)

* feat: indexer genesis state

* chore: update pallet

* Auto-update metadata & TypeScript type definitions

* chore: update CI and prover docs

---------

Co-authored-by: gluwa-bot <creditcoin@gluwa.com>

* feat: segretate indexer (#417)

* Disable type checking

There is this nasty error:

node_modules/@subql/frontier-evm-processor/dist/index.d.ts:5:131 - error TS2724: '"@subql/types"' has no exported member named 'SecondLayerHandlerProcessor_1_0_0'. Did you mean 'SecondLayerHandlerProcessor'?

5 import { SubstrateDatasourceProcessor, SubstrateCustomDatasource, SubstrateHandlerKind, SubstrateCustomHandler, SubstrateMapping, SecondLayerHandlerProcessor_1_0_0 } from '@subql/types';

and you cannot ignore or exclude this file b/c it gets pulled into the
list of files due to imports (whenever we import from
@subql/frontier-evm-processor).

This is something deep inside subql's packages, and I'm not quite sure
what is it exactly. The same error happens with one of the upstream
examples:
https://github.com/subquery/tutorials-frontier-evm-starter

* chore: fix test

* Adjust contract arguments during testing b/c they've changed

* Adjust tests for submitQuery()

to take into account the fact that implementation inside the contract
has changed

* chore: fix test

* Execute tests via wrapper which searches for errors in the logs

to woraround the fact that the tool itself exits with zero status, when
clearly it cannot fetch some blocks:

https://github.com/subquery/subql/issues/2711

* Remove unused handleEvent() mapper function

this isn't hooked up neither in project.ts nor in project.yaml and as
far as I can see is unused.

Also remove other helper functions which were only used by
handleEvent().

* fix: instead of revert, return statuscode (#436)

* fix: instead of revert, return statuscode

* chore: remove redundant code

* fix: code bug

* chore: regenerate abi

* Use symlink instead of duplicating prover.abi.json

WARNING:
requires that we update the build process so that symlinks in the source
directory are dereferenced BEFORE they are sent to the docker build
context!

* Bind mount symlink target inside docker-compose

so that developing with a running container can resolve the symlink

* Update chainId after Devnet was redeployed last Friday

* Produce coverage data when running tests & upload to GitHub

- uses the c8 tool to create reports
- internally relies on NODE_V8_COVERAGE, see https://nodejs.org/api/test.html#collecting-code-coverage

* Experiment with source-map support

* Fix uploads b/c there are files with special characters in their name

at the expense of a slightly broken HTML report (will contain broken
links).

* Add more test scenarios for submitQueryProof()

* Auto-update metadata & TypeScript type definitions

* chore: update devnet

* Simulate proverFee transfer fail in submitQueryProof() test

* Replace Solidity's low-level .call{} with higher level .transfer()

makes it more explicit what we do here and handles reverts automatically
instead of relying on the developer to do that!

* Simulate escrowedAmount transfer fail in reclaimEscrowedPayment()

* Replace Solidity's low-level .call{} with higher level .transfer()

makes it more explicit what we do here and handles reverts automatically
instead of relying on the developer to do that!

---------

Co-authored-by: Alex Todorov <alex.todorov@gluwa.com>
Co-authored-by: rustlang-dev <rust.lang.developer@gmail.com>
Co-authored-by: gluwa-bot <creditcoin@gluwa.com>