Download & use changelog.md from current git checkout dir
fixes
Error: EISDIR: illegal operation on a directory, read

as seen in https://github.com/gluwa/creditcoin3-next/actions/runs/17833467337/job/50708015706

Potentially the action doesn't have permissions to read from /var/tmp