Pin github.com/paritytech/polkadot-sdk@7304295 when building subkey
in https://github.com/paritytech/polkadot-sdk/pull/8714,
https://github.com/paritytech/polkadot-sdk/commit/13bc266c3f3cb337a36998cfdc5940ca559051c9

upstream upgrades the wasmtime crate which no longer compiles with older
rust versions and produces the following error:

```
  Downloaded wasmtime-internal-cranelift v35.0.0
error: failed to compile `subkey v9.0.0 (https://github.com/paritytech/polkadot-sdk#13bc266c)`, intermediate artifacts can be found at `/tmp/cargo-installVI1W08`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  failed to parse manifest at `/home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasmtime-internal-cranelift-35.0.0/Cargo.toml`

Caused by:
  feature `edition2024` is required
```